// src/data/surahs.js

const surahs = [
  { value: "al_fatiha", label: "سورة الفاتحة" },
  { value: "al_baqarah", label: "سورة البقرة" },
  { value: "aal_e_imran", label: "سورة آل عمران" },
  { value: "an_nisa", label: "سورة النساء" },
  { value: "al_ma'idah", label: "سورة المائدة" },
  { value: "al_anam", label: "سورة الأنعام" },
  { value: "al_a'raf", label: "سورة الأعراف" },
  { value: "al_anfal", label: "سورة الأنفال" },
  { value: "at_tawbah", label: "سورة التوبة" },
  { value: "yunus", label: "سورة يونس" },
  { value: "hud", label: "سورة هود" },
  { value: "yusuf", label: "سورة يوسف" },
  { value: "ar_rad", label: "سورة الرعد" },
  { value: "ibrahim", label: "سورة إبراهيم" },
  { value: "al_hijr", label: "سورة الحجر" },
  { value: "an_nahl", label: "سورة النحل" },
  { value: "al_isra", label: "سورة الإسراء" },
  { value: "al_kahf", label: "سورة الكهف" },
  { value: "maryam", label: "سورة مريم" },
  { value: "ta_ha", label: "سورة طه" },
  { value: "al_anbiya", label: "سورة الأنبياء" },
  { value: "al_hajj", label: "سورة الحج" },
  { value: "al_muminun", label: "سورة المؤمنون" },
  { value: "an_nur", label: "سورة النور" },
  { value: "al_furqan", label: "سورة الفرقان" },
  { value: "ash_shuara", label: "سورة الشعراء" },
  { value: "an_naml", label: "سورة النمل" },
  { value: "al_ankabut", label: "سورة العنكبوت" },
  { value: "al_rum", label: "سورة الروم" },
  { value: "luqman", label: "سورة لقمان" },
  { value: "as_sajda", label: "سورة السجدة" },
  { value: "al_ahzab", label: "سورة الأحزاب" },
  { value: "saba", label: "سورة سبأ" },
  { value: "fatir", label: "سورة فاطر" },
  { value: "ya_sin", label: "سورة يس" },
  { value: "as_saffat", label: "سورة الصافات" },
  { value: "sad", label: "سورة ص" },
  { value: "az_zumar", label: "سورة الزمر" },
  { value: "al_mu'min", label: "سورة المؤمن" },
  { value: "hamim_sajda", label: "سورة حم السجدة" },
  { value: "al_jathiya", label: "سورة الجاثية" },
  { value: "al_ahqaf", label: "سورة الأحقاف" },
  { value: "muhammad", label: "سورة محمد" },
  { value: "al_fath", label: "سورة الفتح" },
  { value: "al_hujurat", label: "سورة الحجرات" },
  { value: "qaf", label: "سورة ق" },
  { value: "dhariyat", label: "سورة الذاريات" },
  { value: "at_tur", label: "سورة الطور" },
  { value: "an_najm", label: "سورة النجم" },
  { value: "al_qamar", label: "سورة القمر" },
  { value: "ar_rahman", label: "سورة الرحمن" },
  { value: "al_waqi'a", label: "سورة الواقعة" },
  { value: "al_hadid", label: "سورة الحديد" },
  { value: "al_mutaffifin", label: "سورة المطففين" },
  { value: "al_inshiqaq", label: "سورة الانشقاق" },
  { value: "al_buruj", label: "سورة البروج" },
  { value: "at_takwir", label: "سورة التكوير" },
  { value: "al_infitar", label: "سورة الانفطار" },
  { value: "al_mutaffifin", label: "سورة المطففين" },
  { value: "al_inshiqaq", label: "سورة الانشقاق" },
  { value: "al_buruj", label: "سورة البروج" },
  { value: "at_takwir", label: "سورة التكوير" },
  { value: "al_infitar", label: "سورة الانفطار" },
  { value: "al_mutaffifin", label: "سورة المطففين" },
  { value: "al_inshiqaq", label: "سورة الانشقاق" },
  { value: "al_buruj", label: "سورة البروج" },
  { value: "at_takwir", label: "سورة التكوير" },
  { value: "al_infitar", label: "سورة الانفطار" },
  { value: "al_mutaffifin", label: "سورة المطففين" },
  { value: "al_inshiqaq", label: "سورة الانشقاق" },
  { value: "al_buruj", label: "سورة البروج" },
  { value: "at_takwir", label: "سورة التكوير" },
  { value: "al_infitar", label: "سورة الانفطار" },
];

export default surahs;
