export const CLASSES = {
  1: "1",
  2: "2",
  3: "3",
  4: "4",
};

const surahs = [
  { value: "al_fatiha", label: "سورة الفاتحة" },
  { value: "al_baqarah", label: "سورة البقرة" },
  { value: "aal_e_imran", label: "سورة آل عمران" },
  { value: "an_nisa", label: "سورة النساء" },
  { value: "al_ma'idah", label: "سورة المائدة" },
  { value: "al_anam", label: "سورة الأنعام" },
  { value: "al_a'raf", label: "سورة الأعراف" },
  { value: "al_anfal", label: "سورة الأنفال" },
  { value: "at_tawbah", label: "سورة التوبة" },
  { value: "yunus", label: "سورة يونس" },
  { value: "hud", label: "سورة هود" },
  { value: "yusuf", label: "سورة يوسف" },
  { value: "ar_rad", label: "سورة الرعد" },
  { value: "ibrahim", label: "سورة إبراهيم" },
  { value: "al_hijr", label: "سورة الحجر" },
  { value: "an_nahl", label: "سورة النحل" },
  { value: "al_isra", label: "سورة الإسراء" },
  { value: "al_kahf", label: "سورة الكهف" },
  { value: "maryam", label: "سورة مريم" },
  { value: "ta_ha", label: "سورة طه" },
  { value: "al_anbiya", label: "سورة الأنبياء" },
  { value: "al_hajj", label: "سورة الحج" },
  { value: "al_muminun", label: "سورة المؤمنون" },
  { value: "an_nur", label: "سورة النور" },
  { value: "al_furqan", label: "سورة الفرقان" },
  { value: "ash_shuara", label: "سورة الشعراء" },
  { value: "an_naml", label: "سورة النمل" },
  { value: "al_qasas", label: "سورة القصص" },
  { value: "al_ankabut", label: "سورة العنكبوت" },
  { value: "ar_rum", label: "سورة الروم" },
  { value: "luqman", label: "سورة لقمان" },
  { value: "as_sajda", label: "سورة السجدة" },
  { value: "al_ahzab", label: "سورة الأحزاب" },
  { value: "saba", label: "سورة سبأ" },
  { value: "fatir", label: "سورة فاطر" },
  { value: "ya_sin", label: "سورة يس" },
  { value: "as_saffat", label: "سورة الصافات" },
  { value: "sad", label: "سورة ص" },
  { value: "az_zumar", label: "سورة الزمر" },
  { value: "ghafir", label: "سورة غافر" },
  { value: "fussilat", label: "سورة فصلت" },
  { value: "ash_shura", label: "سورة الشورى" },
  { value: "az_zukhruf", label: "سورة الزخرف" },
  { value: "ad_dukhan", label: "سورة الدخان" },
  { value: "al_jathiya", label: "سورة الجاثية" },
  { value: "al_ahqaf", label: "سورة الأحقاف" },
  { value: "muhammad", label: "سورة محمد" },
  { value: "al_fath", label: "سورة الفتح" },
  { value: "al_hujurat", label: "سورة الحجرات" },
  { value: "qaf", label: "سورة ق" },
  { value: "adh_dhariyat", label: "سورة الذاريات" },
  { value: "at_tur", label: "سورة الطور" },
  { value: "an_najm", label: "سورة النجم" },
  { value: "al_qamar", label: "سورة القمر" },
  { value: "ar_rahman", label: "سورة الرحمن" },
  { value: "al_waqi'a", label: "سورة الواقعة" },
  { value: "al_hadid", label: "سورة الحديد" },
  { value: "al_mujadila", label: "سورة المجادلة" },
  { value: "al_hashr", label: "سورة الحشر" },
  { value: "al_mumtahina", label: "سورة الممتحنة" },
  { value: "as_saff", label: "سورة الصف" },
  { value: "al_jumu'a", label: "سورة الجمعة" },
  { value: "al_munafiqun", label: "سورة المنافقون" },
  { value: "at_taghabun", label: "سورة التغابن" },
  { value: "at_talaq", label: "سورة الطلاق" },
  { value: "at_tahrim", label: "سورة التحريم" },
  { value: "al_mulk", label: "سورة الملك" },
  { value: "al_qalam", label: "سورة القلم" },
  { value: "al_haqqah", label: "سورة الحاقة" },
  { value: "al_ma'arij", label: "سورة المعارج" },
  { value: "nuh", label: "سورة نوح" },
  { value: "al_jinn", label: "سورة الجن" },
  { value: "al_muzzammil", label: "سورة المزمل" },
  { value: "al_muddathir", label: "سورة المدثر" },
  { value: "al_qiyama", label: "سورة القيامة" },
  { value: "al_insan", label: "سورة الإنسان" },
  { value: "al_mursalat", label: "سورة المرسلات" },
  { value: "an_naba", label: "سورة النبأ" },
  { value: "an_naziat", label: "سورة النازعات" },
  { value: "abasa", label: "سورة عبس" },
  { value: "at_takwir", label: "سورة التكوير" },
  { value: "al_infitar", label: "سورة الانفطار" },
  { value: "al_mutaffifin", label: "سورة المطففين" },
  { value: "al_inshiqaq", label: "سورة الانشقاق" },
  { value: "al_buruj", label: "سورة البروج" },
  { value: "at_tarq", label: "سورة الطارق" },
  { value: "al_ala", label: "سورة الأعلى" },
  { value: "al_ghashiya", label: "سورة الغاشية" },
  { value: "al_fajr", label: "سورة الفجر" },
  { value: "al_balad", label: "سورة البلد" },
  { value: "ash_shams", label: "سورة الشمس" },
  { value: "al_layl", label: "سورة الليل" },
  { value: "ad_duha", label: "سورة الضحى" },
  { value: "ash_sharh", label: "سورة الشرح" },
  { value: "at_tin", label: "سورة التين" },
  { value: "al_alaq", label: "سورة العلق" },
  { value: "al_qadr", label: "سورة القدر" },
  { value: "al_bayyina", label: "سورة البينة" },
  { value: "az_zalzalah", label: "سورة الزلزلة" },
  { value: "al_adiyat", label: "سورة العاديات" },
  { value: "al_qariah", label: "سورة القارعة" },
  { value: "at_takathur", label: "سورة التكاثر" },
  { value: "al_asr", label: "سورة العصر" },
  { value: "al_humazah", label: "سورة الهمزة" },
  { value: "al_fil", label: "سورة الفيل" },
  { value: "quraysh", label: "سورة قريش" },
  { value: "al_ma'un", label: "سورة الماعون" },
  { value: "al_kawthar", label: "سورة الكوثر" },
  { value: "al_kafirun", label: "سورة الكافرون" },
  { value: "an_nasr", label: "سورة النصر" },
  { value: "al_masad", label: "سورة المسد" },
  { value: "al_ikhlas", label: "سورة الإخلاص" },
  { value: "al_falaq", label: "سورة الفلق" },
  { value: "an_nas", label: "سورة الناس" },
];

export default surahs;

export const JOB_TYPE = {
  FULL_TIME: "full-time",
  PART_TIME: "part-time",
  INTERNSHIP: "internship",
};

export const JOB_SORT_BY = {
  NEWEST_FIRST: "newest",
  OLDEST_FIRST: "oldest",
  ASCENDING: "a-z",
  DESCENDING: "z-a",
};
export const ROLE = {
  USER: "user",
  ADMIN: "admin",
};
